version: '3.8'

services:
  ai-code-executor:
    build: .
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge
